module.exports.SiteLogo = require('./SiteLogo.js')
module.exports.SiteLogoText = require('./SiteLogoText.js')
module.exports.NewtonCoinIcon = require('./NewtonCoinIcon.js')
module.exports.NewtonLogoFull = require('./NewtonLogoFull.js')
module.exports.HuobiTokenIcon = require('./HuobiTokenIcon.js')
module.exports.BinanceCoinIcon = require('./BinanceCoinIcon.js')
module.exports.HuobiLogoFull = require('./HuobiLogoFull.js')
module.exports.BinanceLogoFull = require('./BinanceLogoFull.js')
